/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 aaron_mha.glb --transform 
Files: aaron_mha.glb [1438.11MB] > /Users/saurav/Programming/Convai/npm_packages/convai-web-handsfree/examples/react-lipsync/public/Aaron_mha/aaron_mha-transformed.glb [1393.69MB] (3%)
Updated with lipsync, head tracking, pupil tracking, and animation support
*/

import React from "react";
import { useGraph, useThree, useFrame } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useHeadTracking } from "../../hooks/useHeadTracking";
import { usePupilTracking } from "../../hooks/usePupilTracking";
import { useMetahumanLipsync } from "../../hooks/useMetahumanLipsync";

// Helper component to ensure geometry is ready
const SafeSkinnedMesh = React.forwardRef(({ geometry, ...props }, ref) => {
  // Only render if geometry has valid attributes
  if (!geometry || !geometry.attributes || !geometry.attributes.position) {
    return null;
  }

  return (
    <skinnedMesh
      ref={ref}
      geometry={geometry}
      frustumCulled={false}
      {...props}
    />
  );
});

export const AaronMha = React.forwardRef(
  (
    {
      meshRefProp,
      convaiClient,
      blendshapeMapping = {},
      onLipsyncUpdate,
      ...props
    },
    characterRef,
  ) => {
    const internalCharacterRef = React.useRef();
    const faceMeshRef = React.useRef(); // Ref for CC_Base_Body (face with morph targets)
    const { scene, animations } = useGLTF(
      "https://huggingface.co/datasets/airsurfer/Aaron/resolve/main/aaron_mha-transformed.glb",
    );
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);
    const { scene: threeScene, gl } = useThree();

    // Enhance material quality on mount - performant settings
    React.useEffect(() => {
      Object.entries(materials).forEach(([name, material]) => {
        if (
          material.isMeshStandardMaterial ||
          material.isMeshPhysicalMaterial
        ) {
          // Identify material types
          const isSkinMaterial =
            name &&
            (name.includes("Skin") ||
              name.includes("Head") ||
              name.includes("Body") ||
              name.includes("Arm") ||
              name.includes("Leg"));

          const isEyeMaterial =
            name &&
            (name.includes("Eye") || name.includes("Cornea")) &&
            !name.includes("Eyelash");

          const isEyelashMaterial = name && name.includes("Eyelash");

          const isHairMaterial =
            name && (name.includes("Hair") || name.includes("Scalp"));

          const isTeethMaterial =
            name && (name.includes("Teeth") || name.includes("Tongue"));

          if (isSkinMaterial) {
            // Skin - natural matte look (less shiny)
            material.envMapIntensity = 0.1; // Reduced from 0.15 for less shine
            material.roughness = 0.85; // Increased from 0.75 for more matte look
            material.metalness = 0.0;
          } else if (isEyeMaterial) {
            // Eyes - very glossy
            material.envMapIntensity = 0.8;
            material.roughness = 0.05;
            material.metalness = 0.0;
          } else if (isEyelashMaterial) {
            // Eyelashes - matte, no shine
            material.envMapIntensity = 0.0;
            material.roughness = 1.0;
            material.metalness = 0.0;
          } else if (isHairMaterial) {
            // Hair - darker shade with noticeable shine
            material.envMapIntensity = 0.35;
            material.roughness = 0.45;
            material.metalness = 0.0;
            // Darken the hair color
            if (material.color) {
              material.color.multiplyScalar(0.35); // Darken to ~35% of original
            }
          } else if (isTeethMaterial) {
            // Teeth & Tongue - slightly darker and more shadowed for natural look
            material.envMapIntensity = 0.12; // Subtle reflections
            material.roughness = 0.45; // Smoother finish for teeth
            material.metalness = 0.0;
            // Darken the teeth/tongue color moderately
            if (material.color) {
              material.color.multiplyScalar(0.65); // Darken to 65% of original
            }
            // Reduce brightness with emissive
            if (material.emissive) {
              material.emissive.setRGB(0, 0, 0);
              material.emissiveIntensity = 0;
            }
          } else {
            // Other materials - increased reflections
            material.envMapIntensity = 0.45;
            material.roughness = material.roughness || 0.4;
            material.metalness = material.metalness || 0.0;
          }

          material.needsUpdate = true;
        }
      });

      // Shadow rendering
      if (gl.shadowMap) {
        gl.shadowMap.enabled = true;
        gl.shadowMap.autoUpdate = true;
      }
    }, [materials, gl]);

    // Callback ref that sets both internal and external refs immediately
    const groupRef = React.useCallback(
      (node) => {
        if (node) {
          // Set internal ref for lipsync (synchronously)
          internalCharacterRef.current = node;

          // Forward to parent if provided
          if (characterRef) {
            if (typeof characterRef === "function") {
              characterRef(node);
            } else {
              characterRef.current = node;
            }
          }
        }
      },
      [characterRef],
    );

    const { actions } = useAnimations(animations, internalCharacterRef);

    // Use the ARKit lipsync hook with modular mapping system (call FIRST to get isPlaying)
    // Available presets: 'ARKIT_TO_CC_EXTENDED', 'ARKIT_TO_RPM', 'ARKIT_TO_ARKIT', 'METAHUMAN_TO_CC5', 'METAHUMAN_TO_CC5_DIRECT'
    // MetaHuman bone names (lowercase CC5 compatible - from console logs)
    const metahumanBones = {
      JAW: "cc_base_jawroot",
      TONGUE_01: "cc_base_tongue01",
      TONGUE_02: "cc_base_tongue02",
      HEAD: "head",
      NECK: "cc_base_necktwist01", // Standard CC5 neck bone (lowercase)
    };

    const { isPlaying, totalFrames } = useMetahumanLipsync({
      convaiClient,
      characterRef: internalCharacterRef,
      scene: threeScene,
      mappingPreset: "METAHUMAN_DIRECT", // Direct MetaHuman mapping
      customMapping: blendshapeMapping, // Optional overrides from props
      boneNames: metahumanBones, // Custom bone configuration for MetaHuman (lowercase)
    });

    // Use the head tracking hook - tracks camera position
    // Tracking strength: 0.7 when speaking, 0.5 when idle
    useHeadTracking(
      nodes.root,
      {
        headOnlyAngle: Math.PI / 3, // 60 degrees each side (head only)
        maxTrackAngle: Math.PI / 2, // 90 degrees each side = 180 degrees total viewing cone
        lerpSpeed: 0.08,
      },
      isPlaying,
    );

    // Use the pupil tracking hook (morph target + bone based)
    // Tracking strength: 1.0 when speaking, 0.5 when idle
    usePupilTracking(
      faceMeshRef,
      nodes.root,
      {
        maxHorizontalAngle: Math.PI / 6, // 30 degrees
        maxVerticalAngle: Math.PI / 8, // 22.5 degrees
        lerpSpeed: 0.2,
        verticalOffset: 0.0, // Offset pupils slightly upward (0.0 to 1.0, where 0.5 is center)
      },
      isPlaying,
    );

    // Play idle animation on repeat with smooth fade-in (like game engines)
    React.useEffect(() => {
      if (actions && Object.keys(actions).length > 0) {
        // Get the first animation (or specific animation if you know the name)
        const firstAnimationName = Object.keys(actions)[0];
        const action = actions[firstAnimationName];

        if (action) {
          // Reset to start position
          action.reset();
          // Set loop mode before playing
          action.setLoop(2, Infinity); // LoopRepeat mode, infinite times
          // Fade in smoothly over 0.5 seconds (like Unreal Engine's blend time)
          action.fadeIn(0.5);
          // Start playing
          action.play();
          console.log(
            `Playing animation: ${firstAnimationName} on repeat (AaronMha) with 0.5s fade-in`,
          );
        }
      }

      // Cleanup - fade out when unmounting
      return () => {
        if (actions) {
          Object.values(actions).forEach((action) => {
            if (action) {
              action.fadeOut(0.3); // Smooth fade out
              // Stop after fade completes
              setTimeout(() => action?.stop(), 300);
            }
          });
        }
      };
    }, [actions]);

    // Pass lipsync state up to parent
    React.useEffect(() => {
      if (onLipsyncUpdate) {
        onLipsyncUpdate({ isPlaying, totalFrames });
      }
    }, [isPlaying, totalFrames, onLipsyncUpdate]);

    // Sync face mesh ref with external meshRefProp
    React.useEffect(() => {
      if (meshRefProp && faceMeshRef.current) {
        meshRefProp.current = faceMeshRef.current;
      }
    }, [meshRefProp]);

    // Debug: Log available nodes to find bone structure
    React.useEffect(() => {
      if (nodes.root) {
        console.log("[AaronMha] Available bones:", Object.keys(nodes));
        console.log("[AaronMha] Root bone:", nodes.root);

        // Traverse skeleton to find jaw and head bones
        nodes.root.traverse((bone) => {
          if (bone.type === "Bone") {
            if (bone.name.toLowerCase().includes("jaw")) {
              console.log("[AaronMha] Found jaw bone:", bone.name);
            }
            if (bone.name.toLowerCase().includes("head")) {
              console.log("[AaronMha] Found head bone:", bone.name);
            }
            if (bone.name.toLowerCase().includes("tongue")) {
              console.log("[AaronMha] Found tongue bone:", bone.name);
            }
          }
        });
      }
    }, [nodes]);

    // Safety check: ensure all required nodes exist
    if (!nodes.root || !nodes.CC_Base_Body) {
      console.warn("AaronMha model not fully loaded yet");
      return null;
    }

    return (
      <group ref={groupRef} {...props} dispose={null}>
        <group name="Scene">
          <group name="Aaron_CC5_HD" scale={0.01}>
            <primitive object={nodes.root} />
          </group>
          <SafeSkinnedMesh
            name="slim_fit_trousers"
            geometry={nodes.slim_fit_trousers.geometry}
            material={materials.Slim_Fit_Trousers_B118}
            skeleton={nodes.slim_fit_trousers.skeleton}
            scale={0.01}
          />
          <SafeSkinnedMesh
            name="sport_sneakers"
            geometry={nodes.sport_sneakers.geometry}
            material={materials.Sport_sneakers_B125}
            skeleton={nodes.sport_sneakers.skeleton}
            scale={0.01}
          />
          <group name="brows" scale={0.01}>
            <SafeSkinnedMesh
              name="Brows"
              geometry={nodes.Brows.geometry}
              material={materials.Brows_Hair_Transparency_B119}
              skeleton={nodes.Brows.skeleton}
              morphTargetDictionary={nodes.Brows.morphTargetDictionary}
              morphTargetInfluences={nodes.Brows.morphTargetInfluences}
            />
            <SafeSkinnedMesh
              name="Brows_1"
              geometry={nodes.Brows_1.geometry}
              material={materials.Brows_Color_Transparency_B120}
              skeleton={nodes.Brows_1.skeleton}
              morphTargetDictionary={nodes.Brows_1.morphTargetDictionary}
              morphTargetInfluences={nodes.Brows_1.morphTargetInfluences}
            />
            <SafeSkinnedMesh
              name="Brows_2"
              geometry={nodes.Brows_2.geometry}
              material={materials.Brows_Base_Transparency_B121}
              skeleton={nodes.Brows_2.skeleton}
              morphTargetDictionary={nodes.Brows_2.morphTargetDictionary}
              morphTargetInfluences={nodes.Brows_2.morphTargetInfluences}
            />
          </group>
          <group name="cc_base_body" scale={0.01}>
            <SafeSkinnedMesh
              ref={faceMeshRef}
              name="CC_Base_Body"
              geometry={nodes.CC_Base_Body.geometry}
              material={materials.Std_Skin_Head_B107}
              skeleton={nodes.CC_Base_Body.skeleton}
              morphTargetDictionary={nodes.CC_Base_Body.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Body.morphTargetInfluences}
            />
            <SafeSkinnedMesh
              name="CC_Base_Body_1"
              geometry={nodes.CC_Base_Body_1.geometry}
              material={materials.Std_Skin_Body_B108}
              skeleton={nodes.CC_Base_Body_1.skeleton}
              morphTargetDictionary={nodes.CC_Base_Body_1.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Body_1.morphTargetInfluences}
            />
            <SafeSkinnedMesh
              name="CC_Base_Body_2"
              geometry={nodes.CC_Base_Body_2.geometry}
              material={materials.Std_Skin_Arm_B109}
              skeleton={nodes.CC_Base_Body_2.skeleton}
              morphTargetDictionary={nodes.CC_Base_Body_2.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Body_2.morphTargetInfluences}
            />
            <SafeSkinnedMesh
              name="CC_Base_Body_3"
              geometry={nodes.CC_Base_Body_3.geometry}
              material={materials.Std_Skin_Leg_B110}
              skeleton={nodes.CC_Base_Body_3.skeleton}
              morphTargetDictionary={nodes.CC_Base_Body_3.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Body_3.morphTargetInfluences}
            />
            <SafeSkinnedMesh
              name="CC_Base_Body_4"
              geometry={nodes.CC_Base_Body_4.geometry}
              material={materials.Std_Nails_B111}
              skeleton={nodes.CC_Base_Body_4.skeleton}
              morphTargetDictionary={nodes.CC_Base_Body_4.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Body_4.morphTargetInfluences}
            />
            <SafeSkinnedMesh
              name="CC_Base_Body_5"
              geometry={nodes.CC_Base_Body_5.geometry}
              material={materials.Std_Eyelash_B112}
              skeleton={nodes.CC_Base_Body_5.skeleton}
              morphTargetDictionary={nodes.CC_Base_Body_5.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Body_5.morphTargetInfluences}
            />
          </group>
          <group name="cc_base_eye" scale={0.01}>
            <SafeSkinnedMesh
              name="CC_Base_Eye"
              geometry={nodes.CC_Base_Eye.geometry}
              material={materials.Std_Eye_R_B100}
              skeleton={nodes.CC_Base_Eye.skeleton}
              morphTargetDictionary={nodes.CC_Base_Eye.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Eye.morphTargetInfluences}
            />
            <SafeSkinnedMesh
              name="CC_Base_Eye_1"
              geometry={nodes.CC_Base_Eye_1.geometry}
              material={materials.Std_Cornea_R_B101}
              skeleton={nodes.CC_Base_Eye_1.skeleton}
              morphTargetDictionary={nodes.CC_Base_Eye_1.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Eye_1.morphTargetInfluences}
            />
            <SafeSkinnedMesh
              name="CC_Base_Eye_2"
              geometry={nodes.CC_Base_Eye_2.geometry}
              material={materials.Std_Eye_L_B102}
              skeleton={nodes.CC_Base_Eye_2.skeleton}
              morphTargetDictionary={nodes.CC_Base_Eye_2.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Eye_2.morphTargetInfluences}
            />
            <SafeSkinnedMesh
              name="CC_Base_Eye_3"
              geometry={nodes.CC_Base_Eye_3.geometry}
              material={materials.Std_Cornea_L_B103}
              skeleton={nodes.CC_Base_Eye_3.skeleton}
              morphTargetDictionary={nodes.CC_Base_Eye_3.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Eye_3.morphTargetInfluences}
            />
          </group>
          <group name="cc_base_eyeocclusion" scale={0.01}>
            <SafeSkinnedMesh
              name="CC_Base_EyeOcclusion"
              geometry={nodes.CC_Base_EyeOcclusion.geometry}
              material={materials.Std_Eye_Occlusion_R_B113}
              skeleton={nodes.CC_Base_EyeOcclusion.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_EyeOcclusion.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_EyeOcclusion.morphTargetInfluences
              }
            />
            <SafeSkinnedMesh
              name="CC_Base_EyeOcclusion_1"
              geometry={nodes.CC_Base_EyeOcclusion_1.geometry}
              material={materials.Std_Eye_Occlusion_R_B113}
              skeleton={nodes.CC_Base_EyeOcclusion_1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_EyeOcclusion_1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_EyeOcclusion_1.morphTargetInfluences
              }
            />
          </group>
          <SafeSkinnedMesh
            name="cc_base_tear_ducts"
            geometry={nodes.cc_base_tear_ducts.geometry}
            material={materials.CC_Base_Tear_Ducts_B104}
            skeleton={nodes.cc_base_tear_ducts.skeleton}
            morphTargetDictionary={
              nodes.cc_base_tear_ducts.morphTargetDictionary
            }
            morphTargetInfluences={
              nodes.cc_base_tear_ducts.morphTargetInfluences
            }
            scale={0.01}
          />
          <group name="cc_base_tearline" scale={0.01}>
            <SafeSkinnedMesh
              name="CC_Base_TearLine"
              geometry={nodes.CC_Base_TearLine.geometry}
              material={materials.Std_Tearline_R_001_B105}
              skeleton={nodes.CC_Base_TearLine.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_TearLine.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_TearLine.morphTargetInfluences
              }
            />
            <SafeSkinnedMesh
              name="CC_Base_TearLine_1"
              geometry={nodes.CC_Base_TearLine_1.geometry}
              material={materials.Std_Tearline_R_001_B105}
              skeleton={nodes.CC_Base_TearLine_1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_TearLine_1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_TearLine_1.morphTargetInfluences
              }
            />
          </group>
          <group name="cc_base_teeth" scale={0.01}>
            <SafeSkinnedMesh
              name="CC_Base_Teeth"
              geometry={nodes.CC_Base_Teeth.geometry}
              material={materials.Std_Upper_Teeth_B122}
              skeleton={nodes.CC_Base_Teeth.skeleton}
              morphTargetDictionary={nodes.CC_Base_Teeth.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Teeth.morphTargetInfluences}
            />
            <SafeSkinnedMesh
              name="CC_Base_Teeth_1"
              geometry={nodes.CC_Base_Teeth_1.geometry}
              material={materials.Std_Lower_Teeth_B123}
              skeleton={nodes.CC_Base_Teeth_1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Teeth_1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Teeth_1.morphTargetInfluences
              }
            />
          </group>
          <SafeSkinnedMesh
            name="cc_base_tongue"
            geometry={nodes.cc_base_tongue.geometry}
            material={materials.Std_Tongue_B115}
            skeleton={nodes.cc_base_tongue.skeleton}
            morphTargetDictionary={nodes.cc_base_tongue.morphTargetDictionary}
            morphTargetInfluences={nodes.cc_base_tongue.morphTargetInfluences}
            scale={0.01}
          />
          <group name="classic_slick_back" scale={0.01}>
            <SafeSkinnedMesh
              name="Classic_Slick_Back"
              geometry={nodes.Classic_Slick_Back.geometry}
              material={materials.Hair_Transparency_B127}
              skeleton={nodes.Classic_Slick_Back.skeleton}
              morphTargetDictionary={
                nodes.Classic_Slick_Back.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Classic_Slick_Back.morphTargetInfluences
              }
            />
            <SafeSkinnedMesh
              name="Classic_Slick_Back_1"
              geometry={nodes.Classic_Slick_Back_1.geometry}
              material={materials.Hair_Clap_Transparency_B128}
              skeleton={nodes.Classic_Slick_Back_1.skeleton}
              morphTargetDictionary={
                nodes.Classic_Slick_Back_1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Classic_Slick_Back_1.morphTargetInfluences
              }
            />
          </group>
          <SafeSkinnedMesh
            name="eyelash_low"
            geometry={nodes.eyelash_low.geometry}
            material={materials.Eyelash_Low_Transparency_B116}
            skeleton={nodes.eyelash_low.skeleton}
            morphTargetDictionary={nodes.eyelash_low.morphTargetDictionary}
            morphTargetInfluences={nodes.eyelash_low.morphTargetInfluences}
            scale={0.01}
          />
          <SafeSkinnedMesh
            name="eyelash_up"
            geometry={nodes.eyelash_up.geometry}
            material={materials.Eyelash_Low_Transparency_B116}
            skeleton={nodes.eyelash_up.skeleton}
            morphTargetDictionary={nodes.eyelash_up.morphTargetDictionary}
            morphTargetInfluences={nodes.eyelash_up.morphTargetInfluences}
            scale={0.01}
          />
          <SafeSkinnedMesh
            name="rs_regular_fit_shirt"
            geometry={nodes.rs_regular_fit_shirt.geometry}
            material={materials.RS_Regular_Fit_Shirt_B124}
            skeleton={nodes.rs_regular_fit_shirt.skeleton}
            morphTargetDictionary={
              nodes.rs_regular_fit_shirt.morphTargetDictionary
            }
            morphTargetInfluences={
              nodes.rs_regular_fit_shirt.morphTargetInfluences
            }
            scale={0.01}
          />
          <SafeSkinnedMesh
            name="stubble"
            geometry={nodes.stubble.geometry}
            material={materials.Beard_Transparency_B126}
            skeleton={nodes.stubble.skeleton}
            morphTargetDictionary={nodes.stubble.morphTargetDictionary}
            morphTargetInfluences={nodes.stubble.morphTargetInfluences}
            scale={0.01}
          />
        </group>
      </group>
    );
  },
);

useGLTF.preload(
  "https://huggingface.co/datasets/airsurfer/Aaron/resolve/main/aaron_mha-transformed.glb",
);
